### ISSUE TITLE
common js support

### ISSUE THREAD

**Issue by DJHammers** [ekwoka/spotify-api#37]
add commonjs support for this npm i use nodejs project (discordbot) and i use commonjs at all the time this is on es6 module i can't use it i need to convert my all codes in to it can you fix this if you can

**Comment by ekwoka** [comment]
You should be able to import it using dynamic imports: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import

as demonstrated here: https://adamcoster.com/blog/commonjs-and-esm-importexport-compatibility-examples

I'd recommend updating to ESM as it is part of the EcmaScript specification. I don't believe there is any real purpose to support non-standard systems.

VSCode has features to easily translate CJS files to spec-compliant ESM modules.
