### ISSUE TITLE
Just thanks for this awsome library ❤️

### ISSUE THREAD

**Issue by MellKam** [ekwoka/spotify-api#66]
I've been watching the javascript libraries for integration with spotify for quite a while and would like to say that this is one of the many projects that really stands out for quality, simplicity and modernity. Many thanks to the author and I wish people would learn about such libraries and stop using outdated solutions like spotify-web-api-js. I am also in the process of making such a library and it was very interesting to see how other people solve the same problems.

**Comment by ekwoka** [comment]
Hopefully, I'll finish it soon lol

I do have some ideas to really push it further for simple ergonomics in common use cases
